# .github/workflows/container_publish.yml
name: Build & publish multi-arch (matrix)

on:
  push:
    branches: [main]       # tweak as needed

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest         # use self-hosted arm64 here to skip QEMU, if you have one
    steps:
      - uses: actions/checkout@v4

      # QEMU is only useful on x86 runners
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push single-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile            # change if needed
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create & push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t $IMAGE_NAME:${{ github.sha }} \
            $IMAGE_NAME:${{ github.sha }}-amd64 \
            $IMAGE_NAME:${{ github.sha }}-arm64
