name: Build & publish multi-arch (matrix)

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runs_on: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runs_on: ubuntu-latest   # or your self-hosted arm node
    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v4

      # Only needed on x86 runners
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push by digest
        id: b
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          # Push *only* this arch and return its digest
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          tags: ${{ env.IMAGE_NAME }}

      # Expose the digest to the merge job
      - name: Export digest
        run: echo "digest=${{ steps.b.outputs.digest }}" >> $GITHUB_OUTPUT
    outputs:
      digest-${{ matrix.arch }}: ${{ steps.b.outputs.digest }}

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create & push manifest
        run: |
          docker buildx imagetools create \
            -t $IMAGE_NAME:${{ github.sha }} \
            $IMAGE_NAME@${{ needs.build.outputs.digest-amd64 }} \
            $IMAGE_NAME@${{ needs.build.outputs.digest-arm64 }}
